import { Inter } from 'next/font/google'
import Sidebar from './components/Sidebar';
import Explorer from './components/Explorer';
import Bottombar from './components/Bottombar';
import Tabsbar from './components/Tabsbar';
import styles from './styles/Layout.module.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} id='main-body'>
        <div className={styles.main}>
          <Sidebar />
          <Explorer />
          <div style={{ width: '100%' }}>
            <Tabsbar />
            <main className={styles.content}>{children}</main>
          </div>
        </div>
        <Bottombar />
      </body>
    </html>
  )
}